import { Metadata } from "next";
import { IRANYekanX } from "@/fonts";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${IRANYekanX.variable} font-iran-yekan-x`}>
        {children}
      </body>
    </html>
  );
}
